# netlify.toml

# Redirect everything to index.html (maintenance page)
[[redirects]]
from = "/*"
to = "/index.html"
status = 503
force = true

# Allow static assets (CSS, JS, images, fonts) to be served normally
[[redirects]]
from = "/styles/*"
to = "/styles/:splat"
status = 200

[[redirects]]
from = "/fonts/*"
to = "/fonts/:splat"
status = 200

[[redirects]]
from = "/images/*"
to = "/images/:splat"
status = 200

[[redirects]]
from = "/js/*"
to = "/js/:splat"
status = 200
